# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  vroom_tester:
    docker:
      # - image: cimg/base:stable
      - image: circleci/python:3.7.4
    working_directory: ~/new_infrastructure

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build_and_test:
    executor: vroom_tester
    steps:
      - checkout
      - run:
          name: Install VROOM_Sandbox
          command: |
            git clone --single-branch --branch ${CIRCLE_BRANCH} https://github.com/TheoPapafotiou/VROOM_Sandbox
            cd VROOM_Sandbox
      - run:
          name: Install Python Dependencies
          command: |
            sudo -H pip3 install --upgrade pip
            sudo pip3 install -r ~/new_infrastructure/VROOM_Sandbox/tests/requirements.txt
      - run:
          name: Run Unit tests
          command: |
            sleep 5
            cd ~/new_infrastructure/VROOM_Sandbox/tests/Lane_keeping
            pytest
          
filters:
  branches:
    only:
      - main
      - circleci-project-setup

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - build_and_test
